class Elements:
    #
    # ID Elements
    #

    spinner = 'calendar-header-spinner'
    add_event_button = 'place-button-add'
    all_appointments_panel = 'all-appointments-panel'
    title_input = 'appointmentTitle'
    location_input = 'appointmentLocation'
    notes_input = 'appointmentBody'
    hours = 'hours'
    minutes = 'minutes'
    ampm = 'amPm'
    day = 'drumDay'
    month = 'drumMonth'
    year = 'drumYear'
    drum_container = 'drum-container'
    drum_hours = 'drum_hours'
    drum_minutes = 'drum_minutes'
    drum_ampm = 'drum_amPm'
    drum_day = 'drum_drumDay'
    drum_month = 'drum_drumMonth'
    drum_year = 'drum_drumYear'
    drum_hours_up = 'dial-up-drum_hours'
    drum_hours_down = 'dial-down-drum_hours'
    drum_minutes_up = 'dial-up-drum_minutes'
    drum_minutes_down = 'dial-down-drum_minutes'
    drum_ampm_up = 'dial-up-drum_amPm'
    drum_ampm_down = 'dial-down-drum_amPm'
    drum_day_up = 'dial-up-drum_drumDay'
    drum_day_down = 'dial-down-drum_drumDay'
    drum_month_up = 'dial-up-drum_drumMonth'
    drum_month_down = 'dial-down-drum_drumMonth'
    drum_year_up = 'dial-up-drum_drumYear'
    drum_year_down = 'dial-down-drum_drumYear'
    yes_edit_button = 'apply-changes-icon'
    close_edit_button = 'close-form-icon'
    delete_event_edit_button = 'delete-event-icon'
    week_selector = 'week-selector'
    weekday_selector = 'weekday-selector'
    day_of_month_selector = 'day-of-month-selector'
    month_selector = 'month-selector'
    edit_prvw = 'edit-appointment-button'
    move_to_prvw = 'move-appointment-button'
    delete_prvw = 'delete-appointment-button'
    show_in_grid_button = 'show-in-grid-button'
    tooltip_panel_button = 'tooltip-panel-btn'

    #
    # Class Name Elements
    #

    title_class = 'title'
    block_wrapper = 'block-wrapper-header'
    bw_button = 'notification-button'
    view_button = 'screen-button'
    today_button = 'today-button'
    all_event_button = 'all-events-button'
    navigation_left = 'navigate-left'
    navigation_right = 'navigate-right'
    navigation_title = 'navigator-title'
    rotated = 'rotated'
    edit_event = 'edit-info'
    all_day_checked = 'all-day-checked'
    color_field = 'color'
    apply_unsaved_changes = 'block-wrapper-header'
    date_error = 'date-error'
    event_name_in_cell = 'subj'
    event_preview = 'CalendarEventPreview'
    # event_name_prvw = 'subject'

    sub_form_tab = 'repeat-subform__tabs__tab'
    day_of_week_cn = 'repeat-subform__select-circles__option'
    sub_wrapper = 'wrapper'
    month_title_year_view = 'month-title'
    no_invitees = 'no-invitees-caption'
    invitees_item = 'invitees-item'
    plus_icon = 'icon-icon_plus'
    contact_items = 'search-contact-item'
    contact_item = 'search-contact-item'
    contact_name = 'name'
    contact_email = 'email'
    data_error_drum = 'date-error'
    contact_search = 'filter-contacts-input'
    clear_search = 'icon-icon_close_filled'
    email_invitees = 'inviteesEmail'
    invitees_count = 'invitees-count'
    location_prvw = 'location'
    notes_prvw = 'notes'
    time_zones_name = 'title'
    alert_title = 'title'
    date_prvw = 'date'
    timezone_text_class = 'timezone-text'
    subject = 'subject'
    button = 'button'
    all_event_title = 'event-title'
    all_event_description = 'event-description'
    tooltip_container_undefined = 'tooltip-container-undefined'

    #
    # Name Elements
    #

    #
    # CSS Selectors
    #
    all_day_button = '.switch.round.small'
    event_name = '#grid-week-event-in-cell-4-1530175067-event-1530178200000 > div > span:nth-child(1)'
    event_name_prvw = '#tooltip-container-undefined > div > div.general-info > div.subject'

    #
    # Xpath Elements
    #
    starts_day_view = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[5]/div[2]'
    starts_other_view = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[5]/div[2]'
    ends_day_view = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[6]/div[2]'
    ends_other_view = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[6]/div[2]'
    timezone = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[3]/div[3]'
    all_day_field = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[4]/div[2]/div/label'
    repeat_field = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[7]/div[3]'
    end_of_repeat_field = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[8]/div[3]'
    end_of_repeat_field_other_view = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[9]/div[3]'
    alert_field = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[9]/div[3]'
    invitees = '//*[@id="rightPanelPlace"]/div/div/div[2]/div[1]/div/div[10]/div[3]'
    yes_apply_unsaved_changes = '//*[@id="close-editor-confirmation"]/div/div[2]'
    no_apply_unsaved_changes = '//*[@id="close-editor-confirmation"]/div/div[3]'
    cancel_apply_unsaved_changes = '//*[@id="close-editor-confirmation"]/div/div[4]'
    overlay = '//*[@id="place-button-add"]/div/div[1]'
    number_day_of_week = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b[1]'
    number_day_of_week_four = '//*[@id="week-selector-option-fourth"]'
    on_day_of_week = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b[2]'
    on_day_of_week_four = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b'
    on_date = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b'
    year_day_of_week_month = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b[1]'
    year_number_day_of_week = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b[2]'
    year_number_day_of_week_four = '//*[@id="week-selector-option-fourth"]'
    year_on_day_of_week = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b[3]'
    year_on_day_of_week_four = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[2]/div/div[3]/b[2]'
    alert_none = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[1]/div[1]'
    alert_value = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[8]/div[3]'
    alert_value_exception = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[7]/div[3]'
    alert_value_repeat = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[10]/div[3]'
    alert_1_hour = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[8]/div[1]'
    timezone_value = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[3]/div[3]'
    selector_for_interval = '//*[@id="interval-selector"]/span'
    selector_for_day_of_month = '//*[@id="day-of-month-selector"]/span'
    selector_for_week = '//*[@id="week-selector"]/span'
    selector_for_weekdays = '//*[@id="weekday-selector"]/span'
    selector_for_month = '//*[@id="month-selector"]/span'
    timezone_disabled = '//*[@id="tooltip-container-undefined"]/div/div/div[2]/div[1]/div/div[3]'
    show_all_occurrences = '#tooltip-container-undefined > div > div:nth-child(4) > span'